version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: houseblog
    ports:
      - "5003:3000"
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
